### PR TITLE
Feature/samja Product Versioning of EXE & DLLs [part1]

### PR DESCRIPTION
**Pull request by jaques-sam**
- Have the product version (e.g. HAL) inside every EXE or DLL build by that project.
- Todo: Also add ability to add the additional labels from the semantic version. That's our proposal:
Possible additional labels:
  - alpha
  - beta
  - pre --> development
  - rc -> releases
  - others? As the spec describes, all these characters are allowed: [0-9A-Za-z-]
Each of these labels couldbe coded with e.g. the first digit, followed by its pre-release version

image

### CODE REVIEW

**Comment by jaques-sam** [comment]
Added the encoding of the string version labels, so please take a look and merge in when possible...
These statuses haven't changed since first push:
> continuous-integration/appveyor/branch Expected — Waiting for status to be reported Required
> continuous-integration/travis-ci Expected — Waiting for status to be reported

**Comment by frederikvannoote** [comment]
> Added the encoding of the string version labels, so please take a look and merge in when possible...
> These statuses haven't changed since first push:
> 
> > continuous-integration/appveyor/branch Expected — Waiting for status to be reported Required
> > continuous-integration/travis-ci Expected — Waiting for status to be reported

I can't change anything about that. You will need to push something to that branch again.

**Comment by jaques-sam** [comment]
> I can't change anything about that. You will need to push something to that branch again.

I did this morning with my second push.
Do you accept this change? I did not include this 'd' for development, let's use 'pre' from now on.

**Comment by jaques-sam** [comment]
Pushing didn't help so far, I try once more...

**Comment by jaques-sam** [comment]
@frederikvannoote  can you solve the issue here. It can be done as explained here: https://github.com/travis-ci/travis-ci/issues/10204:
**Remedy**
To fix this issue, update your repositories using protected branches to require GitHub Checks as follows:

1. Go to the repository’s Branch Settings page (https://github.com/OWNER/REPO/settings/branches).
2. In the "Branch Protection Settings" section, click "Edit" for a protected branch
3. Scroll down to the second box, "Require status checks to pass before merging." Select either "Travis CI - Pull Request" or "Travis CI - Branch" or both. (Note: "continuous-integration/travis-ci" is the Status API event which is deprecated)
4. Save your changes

**Comment by jaques-sam** [comment]
Replaced by https://github.com/cmakespark/cmake/compare/master...feature/samja-versioning

**Pull request closed without merging**
